### PR TITLE
New site layout with images and facebook feeds.

### PR DESCRIPTION
**Pull request by rafaqz**
Hey skud, some code for review.

The site is up here at http://acres-dev.herokuapp.com/

Paperclip will need amazon s3 to run on heroku and aws-sdk gem still, but we don't have an amazon account yet so that will come later.

I also removed non-stupid-digest-assets and reworked all the images to use digest urls, as heroku was breaking in asset:precompile.

Tests are passing, and I've added/reworked a few for new functionality. I didn't test paperclip as its a stock standard usage that's pretty well tested for already, and its not worth the work.

cheers

### CODE REVIEW

**Comment by Skud** [comment]
Hi @rafaqz, thanks so much for this PR!

I'm travelling right now but should be able to take a review pass over this soon.

For starters, could you please clarify in the PR title and description, what features does this PR implement?  Please link to the relevant PT stories as well.  That will help me understand the code in context, and review it more effectively.

A.

**Comment by Skud** [comment]
OK I've taken a quick pass through and the main comment which I have -- and which I'll avoid repeating a zillion times because it's boring :) -- is that I'd like to see feature tests for each significant change in the UI.  I'm not so fussed by eg. things being rearranged on the page, or CSS tweaks, but if there is a major change like eg. "map is now on the sites page" or "show featured sites, which are those which have images, on the homepage" then we should have a feature test for them.

If you haven't written feature tests before, there are a bunch of examples in spec/features which should give you some ideas.  They are written using RSpec+Capybara -- Capybara documentation/syntax is [here](https://github.com/jnicklas/capybara).  If you want further examples, there are some in http://github.com/Growstuff/growstuff where we use a similar system.

I'd also like to see unit tests for any change to the models, eg. if you are changing the default scope, write a unit test for that.  And definitely some tests (and factories to support them) for images overall!

You're probably asleep right now and when you're up I'll be in transit.  I will probably be able to take another pass at reviewing it sometime on Friday or after (I make a policy of not touching code when jetlagged ;))

Thanks again!  It's looking good overall, I'd mostly just like some tests and clearer high-level explanation in the PR text so that it makes sense to anyone looking back over the history.

**Comment by rafaqz** [comment]
Hey thanks for the feedback!

First there are no PT stories, we managed tasks in emails and in person,
and with pdfs with design changes etc. The main brief was to generally
"make things easier and better" so I've been in designer mode as it doesn't
really fit a TDD approach. Its maybe not the most structured process but
its been a very efficient way of doing a redesign without exact specs...
But I'm sure that makes it confusing for you to understand!

So basically the tasks were:

- General look and usability of the website
- Simplify the front page and move the map to sites, and replace it with a
simpler sites listing (that became the featured -sites block)
- Make the cms easier to use
- Add Images to sites.
- Add facebook feed to individual sites.
- Use less statuses for sites.
- Show user emails to admin for people watching each site, and sites nearby.

- Lots of little cosmetic things.


Many of the new features are actually tested, it may have been hard to see
in that massive code dump. But yes there are definitely lots missing too.
I'l go through them here, partly just for me to be thorough!

Existing:

-Featured sites are here:
https://github.com/rafaqz/3000acres/blob/updates/spec/features/sites_spec.rb#L33
(needs a test for normal users not seeing the checkbox)

-General admin panels for site emails etc here:
https://github.com/rafaqz/3000acres/blob/updates/spec/features/sites_spec.rb#L45
https://github.com/rafaqz/3000acres/blob/updates/spec/features/sites_spec.rb#L111

-CMS links are here:
https://github.com/rafaqz/3000acres/blob/updates/spec/features/cms_spec.rb#L15
https://github.com/rafaqz/3000acres/blob/updates/spec/features/cms_spec.rb#L28
(probably we should test the cms edit save process, and clean up the above
tests a little)

-The map is tested as it was previously, except for the sites page.

-The changes to statuses are tested everywhere they were tested before, its
just a reduction in the list of options. Possibly the migration should be
tested.

-Many of the smaller cosmetic changes are also tested with changes to the
original tests that were broken by them.

Missing:

- The get involved box that swaps out for contact details if they exist
should probably be tested.
- Facebook field has no tests as it does nothing of interest currently, but
it really wants validation, and that would need to be tested on the model.
- Paperclip
- Nearby sites/nearby emails/geokit

So...

Feature test to be added:

- Edit/Save cms snippet.
- Get involved/contact details.
- Featured check not visible to normal user.
- Nearby sites and user emails in admin block are actually nearby.
- Paperclip

Model tests to be added:
- geokit nearest users and sites
- facebook with validation
- has many users through watchers

If you can find more specific examples let me know!

Cheers

**Comment by rafaqz** [comment]
BTW, what specific cases do you think are actually worth testing with paperclip images?

**Comment by rafaqz** [comment]
Tests written!

nearby sites, facebook validation, post order, basic image upload, get involved block visibility.

The edit snippet feature in the cms proved to be very time consuming, and its only for admin use so I'm putting that on hold to avoid chewing up the budget for a minor concern. I feel it would be just worth implementing cms fixtures properly if we want to tests snippets, then it will be easy. But it tests that no other users can see the functionality, at least.

**Comment by Skud** [comment]
Hi Raf!

Current status as I see it:

1. Thank you for the tests!  Just what was needed :)  I agree the CMS tests are probably too time-consuming for now.
2. Tests are currently failing. Please can you make sure they pass on Travis-CI?  I can't merge until they do.
3. Please update the title and description of this PR to more clearly explain what features are included.  Eg. the title could be "Photo upload, CMS improvements, improved site layout" and the description should include links to the Pivotal Tracker stories for each one.

When the tests are passing and the PR title/description are updated I will merge and push to production :)

Thanks again!

**Comment by rafaqz** [comment]
Aah its the unstubbed geocoder calls. I was surprised that they worked last time (you will see the last commit passed and the next commit is only minor visual differences, and isn't what broke it) but I went with it. I'll need to stub those in I guess to make it reliable :/

**Comment by rafaqz** [comment]
Stubbed, hope it passes travis! its fine locally but I need to sleep now so can't wait.

As a side effect the specs are super fast now with geocoder stubbed.

**Comment by Skud** [comment]
Geocoder is a PITA to test against :)

I'm going to merge this now.

**Pull request merged**
